name: Push main to rel

on:
  schedule:
      - cron:  '*/5 * * * *'

jobs:
  build:
    name: Push to rel
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

          #      - run: "git push origin main:rel/Test-2.5.0"
      - run: " git status" 
